In [ ]:
import numpy as np
import pandas as pd

In [ ]:
movies=pd.read_csv('/content/drive/MyDrive/tmdb_5000_movies.csv')
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
credits=pd.read_csv('/content/drive/MyDrive/tmdb_5000_credits.csv')
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies=movies.merge(credits,on='title')
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

<!-- # id
# genres
# keywords
# title
# overview
# cast
# crew -->

In [ ]:
movies=movies[['movie_id','title','keywords','genres','overview','cast','crew']]
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
overview    3
cast        0
crew        0
dtype: int64

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.duplicated().sum()

0

In [ ]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

**Extract** name of genre

In [ ]:
import ast

In [ ]:
def convert(x):
  l=[]
  for i in ast.literal_eval(x):
    l.append(i['name'])
  return l

In [ ]:
movies['genres']=movies['genres'].apply(convert)
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

**Extract** name of keywords

In [ ]:
movies['keywords']=movies['keywords'].apply(convert)
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

**Extract** 5 names from cast

In [ ]:
def convert3(x):
  l=[]
  c=0
  for i in ast.literal_eval(x):
    if c!=5:
      l.append(i['name'])
      c+=1
    else:
      break
  return l

In [ ]:
movies['cast']=movies['cast'].apply(convert3)
movies['cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [ ]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

**Extract** job director from crew

In [ ]:
def get_director(x):
  l=[]
  for i in ast.literal_eval(x):
    if i['job']=='Director':
      l.append(i['name'])
      break
  return l

In [ ]:
movies['crew']=movies['crew'].apply(get_director)
movies['crew']

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

**Modify** overview

In [ ]:
movies['overview']=movies['overview'].apply(lambda x:x.split())
movies['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [ ]:
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

**Remove Space**

In [ ]:
from os import replace
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

**Tags = genres + keywords + overview + cast + crew**

In [ ]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
movies.to_csv('movies.csv')
!cp movies.csv "drive/My Drive/"

In [ ]:
new_df=movies[['movie_id','title','tags']]
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [ ]:
new_df.to_csv('new_df.csv')
!cp new_df.csv "drive/My Drive/"

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df['tags']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bondâ€™s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [ ]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez JamesCameron'

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

**steming similar words**

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
def stem(text):
  l1=[]
  for i in text.split():
    l1.append(ps.stem(i))
  return " ".join(l1)

In [ ]:
# Example of steming
print(ps.stem('dance'))
print(ps.stem('dancing'))
print(ps.stem('danced'))

danc
danc
danc

In [ ]:
new_df['tags']=new_df['tags'].apply(stem)
new_df['tags']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

**converting words into vector**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanalda',
 'alanarkin',
 'alanrickman',
 'alaska',
 'albert',
 'albertbrook',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alecguin',
 'alex',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alilart',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allisonjanney',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amypoehl',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'andysamberg',
 'andyserki',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'angelo',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annapaquin',
 'annasophiarobb',
 'anne',
 'annebancroft',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blakel',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'braddourif',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breath',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briancox',
 'briandennehi',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucemcgil',
 'brucewilli',
 'brutal',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charlesd',
 'charlesdurn',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'children',
 'chill',
 'chimcbrid',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chriso',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christoph',
 'christopherlloyd',
 'christophermcdonald',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurti',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collin',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 ...]

**Similarity of one movie to others (closeness in the vectors)**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [ ]:
similarity[0]

array([1.        , 0.08006408, 0.08492078, ..., 0.04441156, 0.        ,
       0.        ])

Index of the movie on the basis of title

In [ ]:
movie_index=new_df[new_df['title']=='Batman Begins'].index[0]
movie_index

119

In [ ]:
#similarity with index
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08006407690254357),
 (2, 0.08492077756084468),
 (3, 0.07161148740394328),
 (4, 0.18685673434682065),
 (5, 0.105129283382795),
 (6, 0.039722906114947866),
 (7, 0.1416576493949657),
 (8, 0.05661385170722978),
 (9, 0.09443843292997713),
 (10, 0.09883324222148016),
 (11, 0.09245003270420486),
 (12, 0.08770580193070292),
 (13, 0.04399058702145837),
 (14, 0.12503908082008883),
 (15, 0.06201736729460422),
 (16, 0.075955452531275),
 (17, 0.13592873654160803),
 (18, 0.09370791409872918),
 (19, 0.0826898230594723),
 (20, 0.05661385170722978),
 (21, 0.10529962529853128),
 (22, 0.06677805632941779),
 (23, 0.08627959628145762),
 (24, 0.053376051268362375),
 (25, 0.033757978902788886),
 (26, 0.1500468969841066),
 (27, 0.18605210188381263),
 (28, 0.10675210253672475),
 (29, 0.06419407387663695),
 (30, 0.06537204504606134),
 (31, 0.1513068831672006),
 (32, 0.0826898230594723),
 (33, 0.09245003270420485),
 (34, 0.0),
 (35, 0.09421114395319916),
 (36, 0.16898159235484367),
 (37, 0.07692307692307693),
 (38, 0.07944581222989573),
 (39, 0.081199794294115),
 (40, 0.07412493166611012),
 (41, 0.1585187847802434),
 (42, 0.0),
 (43, 0.10997646755364593),
 (44, 0.06405126152203486),
 (45, 0.08134518347820842),
 (46, 0.13344012817090595),
 (47, 0.1913897505877382),
 (48, 0.08134518347820842),
 (49, 0.05751973085430508),
 (50, 0.10984700727621793),
 (51, 0.07884165279854434),
 (52, 0.14484136487558028),
 (53, 0.04399058702145837),
 (54, 0.03026137663344012),
 (55, 0.07073278556897407),
 (56, 0.16694514082354447),
 (57, 0.02387049580131443),
 (58, 0.06598588053218755),
 (59, 0.07073278556897407),
 (60, 0.01813094310734737),
 (61, 0.23372319715296228),
 (62, 0.07548513560963972),
 (63, 0.08006407690254357),
 (64, 0.02875986542715254),
 (65, 0.019003715589632167),
 (66, 0.021995293510729184),
 (67, 0.16012815380508713),
 (68, 0.11694106924093722),
 (69, 0.025976216673306556),
 (70, 0.07792865001991967),
 (71, 0.07242068243779014),
 (72, 0.12988108336653278),
 (73, 0.032686022523030676),
 (74, 0.19985201625794738),
 (75, 0.10529962529853128),
 (76, 0.07007127538005775),
 (77, 0.014098497814593786),
 (78, 0.04883862905055043),
 (79, 0.060522753266880225),
 (80, 0.04954787398762882),
 (81, 0.108094949066235),
 (82, 0.07242068243779014),
 (83, 0.177646236673731),
 (84, 0.12201777521731262),
 (85, 0.11208970766356102),
 (86, 0.06862635163075162),
 (87, 0.10826639239215334),
 (88, 0.08770580193070292),
 (89, 0.05706139900145506),
 (90, 0.06163335513613657),
 (91, 0.16477051091432687),
 (92, 0.060522753266880225),
 (93, 0.07007127538005775),
 (94, 0.1754116038614058),
 (95, 0.1358732440973515),
 (96, 0.07502344849205331),
 (97, 0.06862635163075162),
 (98, 0.075955452531275),
 (99, 0.05264981264926564),
 (100, 0.06677805632941779),
 (101, 0.07412493166611012),
 (102, 0.12104550653376046),
 (103, 0.0782510703046739),
 (104, 0.05492350363810897),
 (105, 0.09805806756909202),
 (106, 0.060522753266880225),
 (107, 0.06100888760865632),
 (108, 0.1416576493949657),
 (109, 0.06405126152203486),
 (110, 0.04358136336404089),
 (111, 0.14484136487558028),
 (112, 0.07502344849205331),
 (113, 0.042796049251091296),
 (114, 0.04441155916843275),
 (115, 0.04358136336404089),
 (116, 0.04721921646498856),
 (117, 0.05751973085430508),
 (118, 0.03285760387267628),
 (119, 0.042051713353118),
 (120, 0.0),
 (121, 0.10675210253672475),
 (122, 0.11322770341445956),
 (123, 0.11102889792108188),
 (124, 0.06661733875264912),
 (125, 0.07717081694263092),
 (126, 0.1316245316231641),
 (127, 0.14322297480788657),
 (128, 0.0),
 (129, 0.08968970586617499),
 (130, 0.025976216673306556),
 (131, 0.10256410256410256),
 (132, 0.06537204504606134),
 (133, 0.026688025634181187),
 (134, 0.12326671027227314),
 (135, 0.0),
 (136, 0.022875450543583874),
 (137, 0.02948198280077641),
 (138, 0.1282051282051282),
 (139, 0.11737660545701087),
 (140, 0.04358136336404089),
 (141, 0.08492077756084468),
 (142, 0.08238525545716345),
 (143, 0.08483796839677037),
 (144, 0.04941662111074008),
 (145, 0.01887128390240993),
 (146, 0.015777895820254743),
 (147, 0.05492350363810897),
 (148, 0.09607689228305229),
 (149, 0.15202972471705734),
 (150, 0.1611258466588724),
 (151, 0.1921537845661046),
 (152, 0.08006407690254357),
 (153, 0.07710865759549869),
 (154, 0.06052275326688024),
 (155, 0.02001601922563589),
 (156, 0.06004805767690767),
 (157, 0.09805806756909202),
 (158, 0.12955005512625914),
 (159, 0.06163335513613657),
 (160, 0.11440107883060738),
 (161, 0.03140371465106639),
 (162, 0.03140371465106639),
 (163, 0.05063696835418333),
 (164, 0.08006407690254357),
 (165, 0.04399058702145837),
 (166, 0.1235415527768502),
 (167, 0.08627959628145762),
 (168, 0.16898159235484367),
 (169, 0.0863667034175061),
 (170, 0.10336227882434038),
 (171, 0.022645540682891915),
 (172, 0.20483662259967567),
 (173, 0.022875450543583874),
 (174, 0.07502344849205331),
 (175, 0.06933752452815364),
 (176, 0.02875986542715254),
 (177, 0.0),
 (178, 0.02360960823249428),
 (179, 0.06988565578146122),
 (180, 0.021398024625545648),
 (181, 0.04399058702145837),
 (182, 0.11556254088025608),
 (183, 0.0686701603499473),
 (184, 0.17295817388759027),
 (185, 0.04941662111074008),
 (186, 0.05783149319662402),
 (187, 0.1500468969841066),
 (188, 0.021995293510729184),
 (189, 0.10741723110591492),
 (190, 0.0806970043558403),
 (191, 0.04774099160262886),
 (192, 0.04721921646498856),
 (193, 0.07813453848974924),
 (194, 0.0),
 (195, 0.05661385170722978),
 (196, 0.05063696835418333),
 (197, 0.036031649688745),
 (198, 0.055749467333806056),
 (199, 0.08716272672808179),
 (200, 0.10241831129983783),
 (201, 0.0),
 (202, 0.02973505167250263),
 (203, 0.08006407690254357),
 (204, 0.04883862905055043),
 (205, 0.07548513560963972),
 (206, 0.12691660175143157),
 (207, 0.075955452531275),
 (208, 0.12326671027227314),
 (209, 0.06537204504606135),
 (210, 0.07242068243779014),
 (211, 0.02387049580131443),
 (212, 0.06537204504606134),
 (213, 0.05741692517632145),
 (214, 0.0),
 (215, 0.06537204504606134),
 (216, 0.06280742930213278),
 (217, 0.084103426706236),
 (218, 0.03580574370197164),
 (219, 0.08770580193070292),
 (220, 0.16984155512168933),
 (221, 0.04622501635210243),
 (222, 0.07767356373806174),
 (223, 0.10256410256410256),
 (224, 0.0595843591724218),
 (225, 0.04622501635210243),
 (226, 0.02875986542715254),
 (227, 0.08006407690254357),
 (228, 0.11322770341445958),
 (229, 0.108094949066235),
 (230, 0.0900791242218625),
 (231, 0.0),
 (232, 0.10984700727621793),
 (233, 0.10241831129983783),
 (234, 0.08338763984501665),
 (235, 0.07412493166611012),
 (236, 0.10826639239215334),
 (237, 0.06280742930213278),
 (238, 0.10741723110591493),
 (239, 0.09065471553673685),
 (240, 0.04671418358670517),
 (241, 0.07502344849205331),
 (242, 0.075955452531275),
 (243, 0.09058216273156766),
 (244, 0.09078412990032037),
 (245, 0.07897471897389846),
 (246, 0.07548513560963972),
 (247, 0.0),
 (248, 0.04318335170875305),
 (249, 0.13355611265883557),
 (250, 0.0),
 (251, 0.03883678186903087),
 (252, 0.02001601922563589),
 (253, 0.06477502756312957),
 (254, 0.06793662204867575),
 (255, 0.0),
 (256, 0.10482848367219183),
 (257, 0.05195243334661311),
 (258, 0.017167540087486825),
 (259, 0.06052275326688024),
 (260, 0.19814848097530424),
 (261, 0.02387049580131443),
 (262, 0.10699012312772824),
 (263, 0.09421114395319916),
 (264, 0.0),
 (265, 0.026688025634181187),
 (266, 0.09656090991705352),
 (267, 0.06280742930213278),
 (268, 0.05063696835418333),
 (269, 0.02875986542715254),
 (270, 0.08559209850218259),
 (271, 0.06793662204867575),
 (272, 0.027066598098038335),
 (273, 0.02050230920261824),
 (274, 0.08833906504195108),
 (275, 0.14153462926807445),
 (276, 0.06052275326688024),
 (277, 0.05180118867824779),
 (278, 0.11437725271791938),
 (279, 0.06862635163075162),
 (280, 0.0),
 (281, 0.06362847629757777),
 (282, 0.022205779584216375),
 (283, 0.02632490632463282),
 (284, 0.01813094310734737),
 (285, 0.0186145197762485),
 (286, 0.07710865759549869),
 (287, 0.02470831055537004),
 (288, 0.027066598098038335),
 (289, 0.044844852933087494),
 (290, 0.06052275326688024),
 (291, 0.04828045495852676),
 (292, 0.08362420100070908),
 (293, 0.027874733666903028),
 (294, 0.13937366833451514),
 (295, 0.10390486669322622),
 (296, 0.03942082639927217),
 (297, 0.044844852933087494),
 (298, 0.0),
 (299, 0.05741692517632145),
 (300, 0.1709352016769265),
 (301, 0.09183979479633063),
 (302, 0.06862635163075162),
 (303, 0.027874733666903028),
 (304, 0.06472796978171812),
 (305, 0.1860521018838127),
 (306, 0.08006407690254357),
 (307, 0.10687334289668038),
 (308, 0.06405126152203486),
 (309, 0.06052275326688024),
 (310, 0.03026137663344012),
 (311, 0.14484136487558028),
 (312, 0.09883324222148016),
 (313, 0.05413319619607667),
 (314, 0.0),
 (315, 0.081199794294115),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09421114395319916),
 (320, 0.03140371465106639),
 (321, 0.0),
 (322, 0.20254787341673336),
 (323, 0.029235267310234306),
 (324, 0.025318484177091666),
 (325, 0.09421114395319916),
 (326, 0.05413319619607667),
 (327, 0.02632490632463282),
 (328, 0.026688025634181187),
 (329, 0.075955452531275),
 (330, 0.09767725810110087),
 (331, 0.08968970586617499),
 (332, 0.10675210253672475),
 (333, 0.02387049580131443),
 (334, 0.09548198320525772),
 (335, 0.04441155916843275),
 (336, 0.06827887419989188),
 (337, 0.04441155916843275),
 (338, 0.0),
 (339, 0.04671418358670517),
 (340, 0.04883862905055043),
 (341, 0.08006407690254357),
 (342, 0.15724272550828775),
 (343, 0.019138975058773818),
 (344, 0.029235267310234306),
 (345, 0.022422426466543747),
 (346, 0.0),
 (347, 0.0),
 (348, 0.05751973085430508),
 (349, 0.07325794357582566),
 (350, 0.04828045495852676),
 (351, 0.0),
 (352, 0.027066598098038335),
 (353, 0.04067259173910421),
 (354, 0.021025856676559),
 (355, 0.036031649688745),
 (356, 0.08920515501750789),
 (357, 0.0),
 (358, 0.05947010334500526),
 (359, 0.030816677568068284),
 (360, 0.02050230920261824),
 (361, 0.07502344849205331),
 (362, 0.09245003270420485),
 (363, 0.09855206599818042),
 (364, 0.022875450543583874),
 (365, 0.07325794357582566),
 (366, 0.055749467333806056),
 (367, 0.0),
 (368, 0.12561485860426555),
 (369, 0.1282051282051282),
 (370, 0.04883862905055043),
 (371, 0.09443843292997713),
 (372, 0.04671418358670517),
 (373, 0.1634301126151534),
 (374, 0.037483165639491674),
 (375, 0.060522753266880225),
 (376, 0.04529108136578383),
 (377, 0.0),
 (378, 0.0),
 (379, 0.049813548138671795),
 (380, 0.05063696835418333),
 (381, 0.07767356373806174),
 (382, 0.0),
 (383, 0.042796049251091296),
 (384, 0.02830692585361489),
 (385, 0.0),
 (386, 0.021025856676559),
 (387, 0.023357091793352585),
 (388, 0.0),
 (389, 0.08627959628145762),
 (390, 0.02564102564102564),
 (391, 0.055470019622522904),
 (392, 0.02875986542715254),
 (393, 0.0),
 (394, 0.02387049580131443),
 (395, 0.05128205128205128),
 (396, 0.04358136336404089),
 (397, 0.050015632328035534),
 (398, 0.0),
 (399, 0.022875450543583874),
 (400, 0.08770580193070292),
 (401, 0.029235267310234306),
 (402, 0.07502344849205331),
 (403, 0.08134518347820842),
 (404, 0.06052275326688024),
 (405, 0.05492350363810897),
 (406, 0.020174251088960076),
 (407, 0.020672455764868074),
 (408, 0.030816677568068284),
 (409, 0.0),
 (410, 0.09548198320525772),
 (411, 0.05063696835418333),
 (412, 0.09245003270420486),
 (413, 0.14153462926807445),
 (414, 0.029235267310234306),
 (415, 0.053049589176730555),
 (416, 0.05063696835418333),
 (417, 0.03140371465106639),
 (418, 0.03413943709994594),
 (419, 0.06661733875264912),
 (420, 0.10795837927188262),
 (421, 0.022645540682891915),
 (422, 0.11149893466761211),
 (423, 0.04100461840523648),
 (424, 0.03698001308168194),
 (425, 0.0625407298837625),
 (426, 0.052414241836095915),
 (427, 0.029235267310234306),
 (428, 0.05510387687779837),
 (429, 0.0),
 (430, 0.05063696835418333),
 (431, 0.02360960823249428),
 (432, 0.10997646755364593),
 (433, 0.02973505167250263),
 (434, 0.0),
 (435, 0.033389028164708894),
 (436, 0.0),
 (437, 0.025007816164017767),
 (438, 0.1180480411624714),
 (439, 0.025318484177091666),
 (440, 0.02387049580131443),
 (441, 0.055749467333806056),
 (442, 0.04529108136578383),
 (443, 0.06201736729460422),
 (444, 0.0),
 (445, 0.09767725810110087),
 (446, 0.022422426466543747),
 (447, 0.063077570029677),
 (448, 0.021025856676559),
 (449, 0.10984700727621793),
 (450, 0.02050230920261824),
 (451, 0.024419314525275217),
 (452, 0.03026137663344012),
 (453, 0.02414022747926338),
 (454, 0.11556254088025608),
 (455, 0.06004805767690767),
 (456, 0.04241898419838518),
 (457, 0.08362420100070908),
 (458, 0.042796049251091296),
 (459, 0.033389028164708894),
 (460, 0.023357091793352585),
 (461, 0.13937366833451514),
 (462, 0.031555791640509485),
 (463, 0.03202563076101743),
 (464, 0.0),
 (465, 0.0),
 (466, 0.13977131156292244),
 (467, 0.10423454980627081),
 (468, 0.027066598098038335),
 (469, 0.05868830272850543),
 (470, 0.04441155916843275),
 (471, 0.0625407298837625),
 (472, 0.10390486669322622),
 (473, 0.08968970586617499),
 (474, 0.0),
 (475, 0.042796049251091296),
 (476, 0.12561485860426555),
 (477, 0.0),
 (478, 0.05272904491779212),
 (479, 0.08684168428648435),
 (480, 0.09548198320525772),
 (481, 0.0),
 (482, 0.021398024625545648),
 (483, 0.11894020669001051),
 (484, 0.02875986542715254),
 (485, 0.05063696835418333),
 (486, 0.07927524902574902),
 (487, 0.12326671027227314),
 (488, 0.06571520774535256),
 (489, 0.0),
 (490, 0.13355611265883557),
 (491, 0.09855206599818042),
 (492, 0.07502344849205331),
 (493, 0.02999475137772317),
 (494, 0.0),
 (495, 0.1815682598006407),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06677805632941779),
 (499, 0.0),
 (500, 0.025007816164017767),
 (501, 0.07944581222989573),
 (502, 0.1319717610643751),
 (503, 0.07242068243779014),
 (504, 0.0),
 (505, 0.13355611265883557),
 (506, 0.033389028164708894),
 (507, 0.2545139051903111),
 (508, 0.09767725810110087),
 (509, 0.021398024625545648),
 (510, 0.09656090991705352),
 (511, 0.08770580193070292),
 (512, 0.026688025634181187),
 (513, 0.14484136487558028),
 (514, 0.04721921646498856),
 (515, 0.02470831055537004),
 (516, 0.026688025634181187),
 (517, 0.0),
 (518, 0.04241898419838518),
 (519, 0.0),
 (520, 0.0),
 (521, 0.02414022747926338),
 (522, 0.02387049580131443),
 (523, 0.04721921646498856),
 (524, 0.0),
 (525, 0.04575090108716775),
 (526, 0.027461751819054483),
 (527, 0.03202563076101743),
 (528, 0.022875450543583874),
 (529, 0.16349964255346808),
 (530, 0.053376051268362375),
 (531, 0.04671418358670517),
 (532, 0.020846909961254163),
 (533, 0.05947010334500526),
 (534, 0.08006407690254357),
 (535, 0.09656090991705352),
 (536, 0.10997646755364593),
 (537, 0.06677805632941779),
 (538, 0.0),
 (539, 0.24019223070763068),
 (540, 0.07325794357582566),
 (541, 0.1025115460130912),
 (542, 0.03698001308168194),
 (543, 0.07692307692307693),
 (544, 0.05264981264926564),
 (545, 0.024419314525275217),
 (546, 0.06163335513613657),
 (547, 0.081199794294115),
 (548, 0.0),
 (549, 0.11678545896676293),
 (550, 0.02360960823249428),
 (551, 0.037229039552497),
 (552, 0.0),
 (553, 0.027874733666903028),
 (554, 0.0),
 (555, 0.04422297420116462),
 (556, 0.026688025634181187),
 (557, 0.12209657262637608),
 (558, 0.0),
 (559, 0.029235267310234306),
 (560, 0.03580574370197164),
 (561, 0.03140371465106639),
 (562, 0.05751973085430508),
 (563, 0.02470831055537004),
 (564, 0.08627959628145762),
 (565, 0.042051713353118),
 (566, 0.023357091793352585),
 (567, 0.024419314525275217),
 (568, 0.1373087590952724),
 (569, 0.04774099160262886),
 (570, 0.06405126152203486),
 (571, 0.04134491152973615),
 (572, 0.105129283382795),
 (573, 0.02050230920261824),
 (574, 0.04671418358670517),
 (575, 0.04399058702145837),
 (576, 0.05128205128205128),
 (577, 0.19814848097530424),
 (578, 0.03698001308168194),
 (579, 0.13937366833451514),
 (580, 0.02387049580131443),
 (581, 0.14867525836251314),
 (582, 0.24194822861802104),
 (583, 0.03673591791853225),
 (584, 0.07548513560963972),
 (585, 0.02360960823249428),
 (586, 0.04358136336404089),
 (587, 0.07082882469748285),
 (588, 0.02470831055537004),
 (589, 0.12955005512625914),
 (590, 0.02973505167250263),
 (591, 0.06150692760785473),
 (592, 0.020846909961254163),
 (593, 0.0),
 (594, 0.04774099160262886),
 (595, 0.1585187847802434),
 (596, 0.09058216273156766),
 (597, 0.05751973085430508),
 (598, 0.03413943709994594),
 (599, 0.026970446468757833),
 (600, 0.06793662204867575),
 (601, 0.03320903209244786),
 (602, 0.08968970586617499),
 (603, 0.05264981264926564),
 (604, 0.06405126152203486),
 (605, 0.025976216673306556),
 (606, 0.0),
 (607, 0.05741692517632145),
 (608, 0.0),
 (609, 0.04622501635210243),
 (610, 0.057289189923154626),
 (611, 0.022645540682891915),
 (612, 0.06201736729460422),
 (613, 0.03494282789073061),
 (614, 0.04671418358670517),
 (615, 0.05947010334500526),
 (616, 0.033389028164708894),
 (617, 0.04941662111074008),
 (618, 0.08483796839677037),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06405126152203486),
 (622, 0.021025856676559),
 (623, 0.0),
 (624, 0.09607689228305229),
 (625, 0.03026137663344012),
 (626, 0.081199794294115),
 (627, 0.10741723110591492),
 (628, 0.0),
 (629, 0.04774099160262886),
 (630, 0.02414022747926338),
 (631, 0.04828045495852676),
 (632, 0.075955452531275),
 (633, 0.02120949209919259),
 (634, 0.07242068243779014),
 (635, 0.06477502756312958),
 (636, 0.023112508176051216),
 (637, 0.023357091793352585),
 (638, 0.03202563076101743),
 (639, 0.0),
 (640, 0.0595843591724218),
 (641, 0.0),
 (642, 0.0),
 (643, 0.09767725810110087),
 (644, 0.04828045495852676),
 (645, 0.04358136336404089),
 (646, 0.05128205128205128),
 (647, 0.04671418358670517),
 (648, 0.029235267310234306),
 (649, 0.0),
 (650, 0.05063696835418333),
 (651, 0.0),
 (652, 0.042796049251091296),
 (653, 0.10482848367219183),
 (654, 0.10087125544480038),
 (655, 0.023357091793352585),
 (656, 0.0),
 (657, 0.05092065106881741),
 (658, 0.04721921646498856),
 (659, 0.025007816164017767),
 (660, 0.09245003270420485),
 (661, 0.16269036695641684),
 (662, 0.0),
 (663, 0.0),
 (664, 0.05947010334500526),
 (665, 0.06862635163075162),
 (666, 0.04941662111074008),
 (667, 0.0),
 (668, 0.1307440900921227),
 (669, 0.032686022523030676),
 (670, 0.01697355035627247),
 (671, 0.0888231183368655),
 (672, 0.02875986542715254),
 (673, 0.019861453057473933),
 (674, 0.07242068243779014),
 (675, 0.04399058702145837),
 (676, 0.02830692585361489),
 (677, 0.02470831055537004),
 (678, 0.11503946170861017),
 (679, 0.0),
 (680, 0.07412493166611012),
 (681, 0.027066598098038335),
 (682, 0.019562767576168476),
 (683, 0.04721921646498856),
 (684, 0.0),
 (685, 0.03026137663344012),
 (686, 0.03026137663344012),
 (687, 0.10390486669322622),
 (688, 0.04169381992250833),
 (689, 0.0),
 (690, 0.02414022747926338),
 (691, 0.055749467333806056),
 (692, 0.10604746049596296),
 (693, 0.03202563076101743),
 (694, 0.02120949209919259),
 (695, 0.06405126152203486),
 (696, 0.020846909961254163),
 (697, 0.0),
 (698, 0.042051713353118),
 (699, 0.03673591791853225),
 (700, 0.027461751819054483),
 (701, 0.055749467333806056),
 (702, 0.021790681682020446),
 (703, 0.02120949209919259),
 (704, 0.06537204504606134),
 (705, 0.02360960823249428),
 (706, 0.02120949209919259),
 (707, 0.0),
 (708, 0.02414022747926338),
 (709, 0.02001601922563589),
 (710, 0.0570111467688965),
 (711, 0.05063696835418333),
 (712, 0.0),
 (713, 0.02414022747926338),
 (714, 0.0),
 (715, 0.09607689228305229),
 (716, 0.02632490632463282),
 (717, 0.0),
 (718, 0.04318335170875305),
 (719, 0.0),
 (720, 0.025318484177091666),
 (721, 0.030816677568068284),
 (722, 0.0),
 (723, 0.02414022747926338),
 (724, 0.022875450543583874),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03039738350583688),
 (728, 0.06933752452815364),
 (729, 0.04721921646498856),
 (730, 0.029864054671577652),
 (731, 0.05063696835418333),
 (732, 0.06793662204867575),
 (733, 0.060522753266880225),
 (734, 0.06598588053218755),
 (735, 0.06598588053218755),
 (736, 0.02830692585361489),
 (737, 0.07325794357582566),
 (738, 0.0),
 (739, 0.03673591791853225),
 (740, 0.105129283382795),
 (741, 0.05264981264926564),

In [ ]:
#Sort on the basis of highest similarity (top 5)
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1216, 0.28306925853614895),
 (507, 0.2545139051903111),
 (3730, 0.2506402059138015),
 (582, 0.24194822861802104),
 (539, 0.24019223070763068)]

In [ ]:
def recommend(movie):
  movie_index=new_df[new_df['title']==movie].index[0]
  distances=similarity[movie_index]
  movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movie_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Avatar')

Aliens vs Predator: Requiem
Independence Day
Falcon Rising
Battle: Los Angeles
Titan A.E.

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))